line_length:
    warning: 80
    error: 100
    ignores_function_declarations: false
    ignores_comments: true
    ignores_urls: true

identifier_name:
  min_length: 2
  max_length: 30
  excluded:
    - i

nesting:
  type_level: 4


cyclomatic_complexity:
  warning: 20
  error: 30

opening_brace:
  ignore_multiline_statement_conditions: true
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
