line_length:
    warning: 80
    error: 100
    ignores_comments: true
    ignores_urls: true
    ignores_interpolated_strings: true

identifier_name:
  min_length: 2
  max_length: 30
  excluded:
    - i

nesting:
  type_level: 4

cyclomatic_complexity:
  warning: 15
  error: 20

opening_brace:
  ignore_multiline_statement_conditions: true


function_body_length:
  warning: 75
  error: 100

file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true

large_tuple:
  warning: 4
  error: 5
  
