line_length:
    warning: 80
    error: 100
    ignores_comments: true
    ignores_urls: true
    ignores_interpolated_strings: true


identifier_name:
  min_length: 2
  max_length: 30
  excluded:
    - i

nesting:
  type_level: 4

cyclomatic_complexity:
  warning: 15
  error: 20

opening_brace:
  ignore_multiline_statement_conditions: true
  ignore_multiline_function_signatures: true
  ignore_multiline_type_headers: true


function_body_length:
  warning: 150
  error: 200

function_parameter_count:
  warning: 8
  error: 10

type_body_length:
  warning: 500
  error: 750

file_length:
  warning: 1500
  error: 2000
  ignore_comment_only_lines: true

large_tuple:
  warning: 4
  error: 5

disabled_rules:
  - todo
  - trailing_comma
  - closure_parameter_position
  
