#+TITLE: README
#+AUTHOR: Zaher Hamadeh

* Table Of Content :toc:
- [[#the-language][The language]]
- [[#why][Why]]
- [[#what][What]]
  - [[#the-basics][The basics]]
  - [[#the-not-so-basics][The not so basics]]
- [[#state][State]]
  - [[#milestones][Milestones]]

* [[file:docs/specification.org][The language]]

* Why
Just for fun.

But also a thought experiment.
An opinionated programming language that fits my programming style.

* What
** The basics
PeoPl is a statically typed compiled functional programming language.
An expression only language, which means no statements are allowed in blocks

Functions behave like pipelines, a pipeline of nodes,
nodes are expressions that can be evaluated to a value.
Expressions are:
- literals
  - integers, decimals, booleans, strings
- arithmetic expressions
- function calls
- branching expressions
- identifiers

Expressions behave like functions.
Functions take an input, with extra arguments, and return an output.

Expressions like literals behave like functions that evaluates to themselves,
they take nothing as input.

Expressions are chained using the pipe operator `|>`.

A function input behave like a regular function argument. But has a priviledged syntax.
It is analoguous to *this* or *self* in object methods.
This means OOP method style syntax is also supported.

It doesn't use curly braces to delimit scope.
It is not needed because there's no standalone statements like assignments and loops.

** The not so basics
Peopl is designed to have an expressive type system, using algebraic data types at its core.
The type system plays well with the expression based syntax for function blocks.

Peopl is also designed to have a powerful and expressive generics system.


* State
Ok nothing is ready, if you find this repo by mistake, just know that nothing is ready.

Todo list:
- [-] Treesitter grammar version 0.1.0.0
  - [X] Type system
    - [X] Tuples
    - [X] Choices
    - [X] Subsets
    - [X] Generics
    - [X] Functions
  - [X] Expressions
    - [X] Arithmetic expressions
    - [X] Function calls
    - [X] Initializers
    - [X] Branching
    - [X] Pattern Matching
  - [ ] Namespaces
    - [ ] Definining namespaces
    - [ ] Importing scopes
- [ ] Parser based on Treesitter
- [ ] Semantic Analyzer
  - [ ] Type definitions check
    - [ ] Checking invalid definitions
    - [ ] Checking redefinitions
    - [ ] Checking shadowing
    - [ ] Checking cyclical definitions
  - [ ] Expressions type checking
    - [ ] Basic piping type checking
    - [ ] Function call type checking
    - [ ] Branching type checking
      - [ ] Exhaustive branching
    - [ ] Lambdas type checking
    - [ ] Type checking with generics
- [ ] Backend
  - [ ] LLVM

** Milestones
*** Version 0.0.1.0

Will be released when a full horizontal implementation (frontend to backend) is acheived.
Included features:
- Working function calls with builtin types
- Exhaustive branching
 
*** Version 0.0.10.0

Working type system

*** Version 0.0.20.0

Manual memory management with Unsafe references
At some point before 0.1 I need to figure out the memory management model

*** Version 0.1.0.0

Working lambdas

*** Version 0.3.0.0

Figure out namespacing

*** Version 0.3.0.0

Working generic system

*** Version 1.0.0.0

Version 1 might never come to life.
But if it does, the goal is to have a set of usable working features,
in addition to couple of stuff:
- A rich core library
- An http library
- File streams
- Strong concurency system
