#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 13

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_identifier = 2,
  anon_sym_BSLASH = 3,
  anon_sym_SQUOTE = 4,
  anon_sym_COLON = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_DOT = 9,
  sym_nothing = 10,
  sym_never = 11,
  sym_int_literal = 12,
  sym_float_literal = 13,
  sym_string_literal = 14,
  anon_sym_true = 15,
  anon_sym_false = 16,
  anon_sym_STAR = 17,
  anon_sym_SLASH = 18,
  anon_sym_PERCENT = 19,
  anon_sym_PLUS = 20,
  anon_sym_DASH = 21,
  anon_sym_EQ = 22,
  anon_sym_BANG_EQ = 23,
  anon_sym_GT = 24,
  anon_sym_GT_EQ = 25,
  anon_sym_LT = 26,
  anon_sym_LT_EQ = 27,
  sym_not_operator = 28,
  sym_and_operator = 29,
  sym_or_operator = 30,
  sym_source_file = 31,
  sym_qualified_identifier = 32,
  sym_definition = 33,
  sym_nominal = 34,
  sym_round_expression_list = 35,
  sym_tagged_expression = 36,
  sym__basic_expression = 37,
  sym__expression = 38,
  sym__complex_expression = 39,
  sym_access_expression = 40,
  sym_call_expression = 41,
  sym_literal = 42,
  sym_bool_literal = 43,
  sym_unary_expression = 44,
  sym_binary_expression = 45,
  sym_multiplicative_operator = 46,
  sym_additive_operator = 47,
  sym_comparative_operator = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_round_expression_list_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [sym_nothing] = "nothing",
  [sym_never] = "never",
  [sym_int_literal] = "int_literal",
  [sym_float_literal] = "float_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [sym_not_operator] = "not_operator",
  [sym_and_operator] = "and_operator",
  [sym_or_operator] = "or_operator",
  [sym_source_file] = "source_file",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_definition] = "definition",
  [sym_nominal] = "nominal",
  [sym_round_expression_list] = "round_expression_list",
  [sym_tagged_expression] = "tagged_expression",
  [sym__basic_expression] = "_basic_expression",
  [sym__expression] = "_expression",
  [sym__complex_expression] = "_complex_expression",
  [sym_access_expression] = "access_expression",
  [sym_call_expression] = "call_expression",
  [sym_literal] = "literal",
  [sym_bool_literal] = "bool_literal",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_multiplicative_operator] = "multiplicative_operator",
  [sym_additive_operator] = "additive_operator",
  [sym_comparative_operator] = "comparative_operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_round_expression_list_repeat1] = "round_expression_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_nothing] = sym_nothing,
  [sym_never] = sym_never,
  [sym_int_literal] = sym_int_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [sym_not_operator] = sym_not_operator,
  [sym_and_operator] = sym_and_operator,
  [sym_or_operator] = sym_or_operator,
  [sym_source_file] = sym_source_file,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_definition] = sym_definition,
  [sym_nominal] = sym_nominal,
  [sym_round_expression_list] = sym_round_expression_list,
  [sym_tagged_expression] = sym_tagged_expression,
  [sym__basic_expression] = sym__basic_expression,
  [sym__expression] = sym__expression,
  [sym__complex_expression] = sym__complex_expression,
  [sym_access_expression] = sym_access_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_literal] = sym_literal,
  [sym_bool_literal] = sym_bool_literal,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_multiplicative_operator] = sym_multiplicative_operator,
  [sym_additive_operator] = sym_additive_operator,
  [sym_comparative_operator] = sym_comparative_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_round_expression_list_repeat1] = aux_sym_round_expression_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_nothing] = {
    .visible = true,
    .named = true,
  },
  [sym_never] = {
    .visible = true,
    .named = true,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_not_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_and_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_or_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_nominal] = {
    .visible = true,
    .named = true,
  },
  [sym_round_expression_list] = {
    .visible = true,
    .named = true,
  },
  [sym_tagged_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__basic_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__complex_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_access_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicative_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_additive_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_comparative_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_round_expression_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_definition = 2,
  field_expression = 3,
  field_field = 4,
  field_identifier = 5,
  field_left = 6,
  field_operand = 7,
  field_operator = 8,
  field_prefix = 9,
  field_right = 10,
  field_scope = 11,
  field_type_specifier = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_definition] = "definition",
  [field_expression] = "expression",
  [field_field] = "field",
  [field_identifier] = "identifier",
  [field_left] = "left",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_prefix] = "prefix",
  [field_right] = "right",
  [field_scope] = "scope",
  [field_type_specifier] = "type_specifier",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 3},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 3},
  [10] = {.index = 18, .length = 2},
  [11] = {.index = 20, .length = 2},
  [12] = {.index = 22, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifier, 0},
  [1] =
    {field_identifier, 2},
    {field_scope, 0},
  [3] =
    {field_arguments, 0},
  [4] =
    {field_definition, 2},
    {field_identifier, 0},
  [6] =
    {field_operand, 1},
    {field_operator, 0},
  [8] =
    {field_arguments, 1},
    {field_prefix, 0},
  [10] =
    {field_definition, 4},
    {field_identifier, 0},
    {field_type_specifier, 2},
  [13] =
    {field_field, 2},
    {field_prefix, 0},
  [15] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [18] =
    {field_expression, 2},
    {field_identifier, 0},
  [20] =
    {field_identifier, 0},
    {field_type_specifier, 2},
  [22] =
    {field_expression, 4},
    {field_identifier, 0},
    {field_type_specifier, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 2,
  [7] = 4,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 14,
  [22] = 16,
  [23] = 17,
  [24] = 18,
  [25] = 19,
  [26] = 13,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 28,
  [35] = 32,
  [36] = 33,
  [37] = 29,
  [38] = 30,
  [39] = 27,
  [40] = 31,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 41,
  [49] = 42,
  [50] = 46,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 53,
  [60] = 54,
  [61] = 58,
  [62] = 56,
  [63] = 55,
  [64] = 52,
  [65] = 47,
  [66] = 57,
  [67] = 51,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 73,
  [78] = 75,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 86,
  [88] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '!', 11,
        '"', 9,
        '%', 74,
        '\'', 54,
        '(', 56,
        ')', 58,
        '*', 72,
        '+', 75,
        ',', 57,
        '-', 76,
        '.', 59,
        '/', 73,
        '0', 62,
        ':', 55,
        '<', 81,
        '=', 77,
        '>', 79,
        'N', 35,
      );
      if (lookahead == '\\') SKIP(21);
      if (lookahead == 'a') ADVANCE(42);
      if (lookahead == 'f') ADVANCE(33);
      if (lookahead == 'n') ADVANCE(44);
      if (lookahead == 'o') ADVANCE(45);
      if (lookahead == 't') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(7);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\r') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '!', 11,
        '%', 74,
        '\'', 54,
        '(', 56,
        ')', 58,
        '*', 72,
        '+', 75,
        ',', 57,
        '-', 76,
        '.', 59,
        '/', 73,
        ':', 55,
        '<', 81,
        '=', 77,
        '>', 79,
        '\\', 53,
        'a', 13,
        'o', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '!', 11,
        '%', 74,
        '(', 56,
        ')', 58,
        '*', 72,
        '+', 75,
        ',', 57,
        '-', 76,
        '.', 59,
        '/', 73,
        ':', 55,
        '<', 81,
        '=', 77,
        '>', 79,
      );
      if (lookahead == '\\') SKIP(4);
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '"', 9,
        '(', 56,
        ')', 58,
        '+', 75,
        ',', 57,
        '-', 76,
        '/', 10,
        '0', 62,
        'N', 35,
      );
      if (lookahead == '\\') SKIP(2);
      if (lookahead == 'f') ADVANCE(33);
      if (lookahead == 'n') ADVANCE(44);
      if (lookahead == 't') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(78);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(84);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 15:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(64);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(65);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 20:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 21:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(20);
      END_STATE();
    case 22:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') SKIP(28);
      END_STATE();
    case 23:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') SKIP(28);
      if (lookahead == '\r') SKIP(22);
      END_STATE();
    case 24:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') SKIP(27);
      END_STATE();
    case 25:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') SKIP(27);
      if (lookahead == '\r') SKIP(24);
      END_STATE();
    case 26:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '!', 11,
        '%', 74,
        '(', 56,
        '*', 72,
        '+', 75,
        '-', 76,
        '.', 59,
        '/', 73,
        '<', 81,
        '=', 77,
        '>', 79,
        '\\', 53,
        'a', 42,
        'o', 45,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 27:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '!', 11,
        '%', 74,
        '(', 56,
        '*', 72,
        '+', 75,
        '-', 76,
        '.', 59,
        '/', 73,
        '<', 81,
        '=', 77,
        '>', 79,
      );
      if (lookahead == '\\') SKIP(25);
      if (lookahead == 'a') ADVANCE(42);
      if (lookahead == 'o') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '\\') SKIP(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_nothing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_never);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '_') ADVANCE(66);
      if (lookahead == 'b') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(16);
      if (lookahead == 'x') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '_') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_not_operator);
      if (lookahead == 'h') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_and_operator);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_and_operator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_or_operator);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_or_operator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 27},
  [34] = {.lex_state = 27},
  [35] = {.lex_state = 27},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 27},
  [38] = {.lex_state = 27},
  [39] = {.lex_state = 27},
  [40] = {.lex_state = 27},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 26},
  [49] = {.lex_state = 26},
  [50] = {.lex_state = 26},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 27},
  [60] = {.lex_state = 27},
  [61] = {.lex_state = 27},
  [62] = {.lex_state = 27},
  [63] = {.lex_state = 27},
  [64] = {.lex_state = 27},
  [65] = {.lex_state = 27},
  [66] = {.lex_state = 27},
  [67] = {.lex_state = 27},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 8},
  [70] = {.lex_state = 8},
  [71] = {.lex_state = 28},
  [72] = {.lex_state = 28},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 28},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 28},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 28},
  [86] = {.lex_state = 28},
  [87] = {.lex_state = 28},
  [88] = {.lex_state = 28},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_nothing] = ACTIONS(1),
    [sym_never] = ACTIONS(1),
    [sym_int_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [sym_not_operator] = ACTIONS(1),
    [sym_and_operator] = ACTIONS(1),
    [sym_or_operator] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(84),
    [sym_qualified_identifier] = STATE(76),
    [sym_definition] = STATE(72),
    [aux_sym_source_file_repeat1] = STATE(72),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
  },
  [2] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym_tagged_expression] = STATE(75),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(75),
    [sym__complex_expression] = STATE(75),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(13),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
  [3] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym_tagged_expression] = STATE(79),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(79),
    [sym__complex_expression] = STATE(79),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(27),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
  [4] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym_tagged_expression] = STATE(79),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(79),
    [sym__complex_expression] = STATE(79),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(29),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
  [5] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym_tagged_expression] = STATE(79),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(79),
    [sym__complex_expression] = STATE(79),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(31),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
  [6] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym_tagged_expression] = STATE(78),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(78),
    [sym__complex_expression] = STATE(78),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(33),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
  [7] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym_tagged_expression] = STATE(79),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(79),
    [sym__complex_expression] = STATE(79),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(35),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
  [8] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(80),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(39),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
  [9] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym_tagged_expression] = STATE(79),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(79),
    [sym__complex_expression] = STATE(79),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
  [10] = {
    [sym_qualified_identifier] = STATE(46),
    [sym_nominal] = STATE(36),
    [sym_round_expression_list] = STATE(54),
    [sym__basic_expression] = STATE(36),
    [sym__expression] = STATE(82),
    [sym_access_expression] = STATE(36),
    [sym_call_expression] = STATE(36),
    [sym_literal] = STATE(36),
    [sym_bool_literal] = STATE(53),
    [sym_unary_expression] = STATE(36),
    [sym_binary_expression] = STATE(36),
    [sym_additive_operator] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(41),
    [anon_sym_RPAREN] = ACTIONS(41),
    [sym_nothing] = ACTIONS(15),
    [sym_never] = ACTIONS(15),
    [sym_int_literal] = ACTIONS(17),
    [sym_float_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_not_operator] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_int_literal,
    ACTIONS(55), 1,
      sym_not_operator,
    STATE(26), 1,
      sym_additive_operator,
    STATE(50), 1,
      sym_qualified_identifier,
    STATE(59), 1,
      sym_bool_literal,
    STATE(60), 1,
      sym_round_expression_list,
    STATE(81), 1,
      sym__expression,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      sym_nothing,
      sym_never,
    ACTIONS(51), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [56] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_int_literal,
    ACTIONS(55), 1,
      sym_not_operator,
    STATE(26), 1,
      sym_additive_operator,
    STATE(50), 1,
      sym_qualified_identifier,
    STATE(59), 1,
      sym_bool_literal,
    STATE(60), 1,
      sym_round_expression_list,
    STATE(83), 1,
      sym__expression,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      sym_nothing,
      sym_never,
    ACTIONS(51), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [112] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_int_literal,
    ACTIONS(25), 1,
      sym_not_operator,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(13), 1,
      sym_additive_operator,
    STATE(46), 1,
      sym_qualified_identifier,
    STATE(53), 1,
      sym_bool_literal,
    STATE(54), 1,
      sym_round_expression_list,
    ACTIONS(19), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(57), 2,
      sym_nothing,
      sym_never,
    STATE(32), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [165] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_int_literal,
    ACTIONS(25), 1,
      sym_not_operator,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(13), 1,
      sym_additive_operator,
    STATE(46), 1,
      sym_qualified_identifier,
    STATE(53), 1,
      sym_bool_literal,
    STATE(54), 1,
      sym_round_expression_list,
    ACTIONS(19), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(59), 2,
      sym_nothing,
      sym_never,
    STATE(29), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [218] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_int_literal,
    ACTIONS(25), 1,
      sym_not_operator,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(13), 1,
      sym_additive_operator,
    STATE(46), 1,
      sym_qualified_identifier,
    STATE(53), 1,
      sym_bool_literal,
    STATE(54), 1,
      sym_round_expression_list,
    ACTIONS(19), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(61), 2,
      sym_nothing,
      sym_never,
    STATE(43), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [271] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_int_literal,
    ACTIONS(25), 1,
      sym_not_operator,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(13), 1,
      sym_additive_operator,
    STATE(46), 1,
      sym_qualified_identifier,
    STATE(53), 1,
      sym_bool_literal,
    STATE(54), 1,
      sym_round_expression_list,
    ACTIONS(19), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(63), 2,
      sym_nothing,
      sym_never,
    STATE(30), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [324] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_int_literal,
    ACTIONS(25), 1,
      sym_not_operator,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(13), 1,
      sym_additive_operator,
    STATE(46), 1,
      sym_qualified_identifier,
    STATE(53), 1,
      sym_bool_literal,
    STATE(54), 1,
      sym_round_expression_list,
    ACTIONS(19), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(65), 2,
      sym_nothing,
      sym_never,
    STATE(31), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [377] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_int_literal,
    ACTIONS(25), 1,
      sym_not_operator,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(13), 1,
      sym_additive_operator,
    STATE(46), 1,
      sym_qualified_identifier,
    STATE(53), 1,
      sym_bool_literal,
    STATE(54), 1,
      sym_round_expression_list,
    ACTIONS(19), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      sym_nothing,
      sym_never,
    STATE(28), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [430] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_int_literal,
    ACTIONS(25), 1,
      sym_not_operator,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(13), 1,
      sym_additive_operator,
    STATE(46), 1,
      sym_qualified_identifier,
    STATE(53), 1,
      sym_bool_literal,
    STATE(54), 1,
      sym_round_expression_list,
    ACTIONS(19), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(69), 2,
      sym_nothing,
      sym_never,
    STATE(27), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [483] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_int_literal,
    ACTIONS(25), 1,
      sym_not_operator,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(13), 1,
      sym_additive_operator,
    STATE(46), 1,
      sym_qualified_identifier,
    STATE(53), 1,
      sym_bool_literal,
    STATE(54), 1,
      sym_round_expression_list,
    ACTIONS(19), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(71), 2,
      sym_nothing,
      sym_never,
    STATE(45), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [536] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_int_literal,
    ACTIONS(55), 1,
      sym_not_operator,
    STATE(26), 1,
      sym_additive_operator,
    STATE(50), 1,
      sym_qualified_identifier,
    STATE(59), 1,
      sym_bool_literal,
    STATE(60), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(51), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(73), 2,
      sym_nothing,
      sym_never,
    STATE(37), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [589] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_int_literal,
    ACTIONS(55), 1,
      sym_not_operator,
    STATE(26), 1,
      sym_additive_operator,
    STATE(50), 1,
      sym_qualified_identifier,
    STATE(59), 1,
      sym_bool_literal,
    STATE(60), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(51), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(75), 2,
      sym_nothing,
      sym_never,
    STATE(38), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [642] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_int_literal,
    ACTIONS(55), 1,
      sym_not_operator,
    STATE(26), 1,
      sym_additive_operator,
    STATE(50), 1,
      sym_qualified_identifier,
    STATE(59), 1,
      sym_bool_literal,
    STATE(60), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(51), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(77), 2,
      sym_nothing,
      sym_never,
    STATE(40), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [695] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_int_literal,
    ACTIONS(55), 1,
      sym_not_operator,
    STATE(26), 1,
      sym_additive_operator,
    STATE(50), 1,
      sym_qualified_identifier,
    STATE(59), 1,
      sym_bool_literal,
    STATE(60), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(51), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(79), 2,
      sym_nothing,
      sym_never,
    STATE(34), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [748] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_int_literal,
    ACTIONS(55), 1,
      sym_not_operator,
    STATE(26), 1,
      sym_additive_operator,
    STATE(50), 1,
      sym_qualified_identifier,
    STATE(59), 1,
      sym_bool_literal,
    STATE(60), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(51), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 2,
      sym_nothing,
      sym_never,
    STATE(39), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [801] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_int_literal,
    ACTIONS(55), 1,
      sym_not_operator,
    STATE(26), 1,
      sym_additive_operator,
    STATE(50), 1,
      sym_qualified_identifier,
    STATE(59), 1,
      sym_bool_literal,
    STATE(60), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(51), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(53), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(83), 2,
      sym_nothing,
      sym_never,
    STATE(35), 7,
      sym_nominal,
      sym__basic_expression,
      sym_access_expression,
      sym_call_expression,
      sym_literal,
      sym_unary_expression,
      sym_binary_expression,
  [854] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(89), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(85), 13,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [896] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(85), 9,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [944] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(95), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(85), 5,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_and_operator,
      sym_or_operator,
  [994] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(99), 1,
      sym_and_operator,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(85), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
    ACTIONS(95), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1046] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(85), 11,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1092] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(103), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(101), 13,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1134] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(109), 1,
      anon_sym_DOT,
    ACTIONS(111), 1,
      sym_and_operator,
    ACTIONS(113), 1,
      sym_or_operator,
    STATE(23), 1,
      sym_additive_operator,
    STATE(24), 1,
      sym_comparative_operator,
    STATE(25), 1,
      sym_multiplicative_operator,
    STATE(65), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(95), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1189] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DOT,
    STATE(23), 1,
      sym_additive_operator,
    STATE(24), 1,
      sym_comparative_operator,
    STATE(25), 1,
      sym_multiplicative_operator,
    STATE(65), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(89), 5,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
  [1236] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      anon_sym_DOT,
    STATE(23), 1,
      sym_additive_operator,
    STATE(24), 1,
      sym_comparative_operator,
    STATE(25), 1,
      sym_multiplicative_operator,
    STATE(65), 1,
      sym_round_expression_list,
    ACTIONS(103), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(101), 9,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1277] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(99), 1,
      sym_and_operator,
    ACTIONS(115), 1,
      sym_or_operator,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(105), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(95), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1330] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DOT,
    STATE(23), 1,
      sym_additive_operator,
    STATE(24), 1,
      sym_comparative_operator,
    STATE(25), 1,
      sym_multiplicative_operator,
    STATE(65), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 3,
      sym_identifier,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(95), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1381] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DOT,
    ACTIONS(111), 1,
      sym_and_operator,
    STATE(23), 1,
      sym_additive_operator,
    STATE(24), 1,
      sym_comparative_operator,
    STATE(25), 1,
      sym_multiplicative_operator,
    STATE(65), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 2,
      sym_identifier,
      sym_or_operator,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(95), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1434] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      anon_sym_DOT,
    STATE(23), 1,
      sym_additive_operator,
    STATE(24), 1,
      sym_comparative_operator,
    STATE(25), 1,
      sym_multiplicative_operator,
    STATE(65), 1,
      sym_round_expression_list,
    ACTIONS(89), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(85), 9,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1475] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DOT,
    STATE(23), 1,
      sym_additive_operator,
    STATE(24), 1,
      sym_comparative_operator,
    STATE(25), 1,
      sym_multiplicative_operator,
    STATE(65), 1,
      sym_round_expression_list,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(89), 5,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1520] = 3,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_BSLASH,
    ACTIONS(121), 19,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1548] = 3,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_BSLASH,
    ACTIONS(125), 19,
      anon_sym_SQUOTE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1576] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(99), 1,
      sym_and_operator,
    ACTIONS(115), 1,
      sym_or_operator,
    ACTIONS(127), 1,
      anon_sym_COLON,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(95), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1628] = 5,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_BSLASH,
    ACTIONS(129), 1,
      anon_sym_SQUOTE,
    ACTIONS(131), 1,
      anon_sym_COLON,
    ACTIONS(121), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1660] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_DOT,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(99), 1,
      sym_and_operator,
    ACTIONS(115), 1,
      sym_or_operator,
    ACTIONS(133), 1,
      anon_sym_COLON,
    STATE(17), 1,
      sym_additive_operator,
    STATE(18), 1,
      sym_comparative_operator,
    STATE(19), 1,
      sym_multiplicative_operator,
    STATE(47), 1,
      sym_round_expression_list,
    ACTIONS(23), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(95), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1712] = 3,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_BSLASH,
    ACTIONS(137), 18,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1739] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(139), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1765] = 3,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(121), 16,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1791] = 3,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(125), 16,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1817] = 4,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(145), 1,
      anon_sym_BSLASH,
    ACTIONS(137), 16,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_LT,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1845] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(147), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1871] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(151), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1897] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(155), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1923] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(159), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1949] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(163), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [1975] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(167), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [2001] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(171), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [2027] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 3,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(175), 15,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym_and_operator,
      sym_or_operator,
  [2053] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(155), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2078] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(159), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2103] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(175), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2128] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(167), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2153] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(163), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2178] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(151), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2203] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(139), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2228] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(171), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 6,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      sym_and_operator,
      sym_or_operator,
    ACTIONS(147), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2278] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 5,
      anon_sym_LPAREN,
      sym_float_literal,
      sym_string_literal,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(179), 7,
      sym_identifier,
      sym_nothing,
      sym_never,
      sym_int_literal,
      anon_sym_true,
      anon_sym_false,
      sym_not_operator,
  [2298] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 5,
      anon_sym_LPAREN,
      sym_float_literal,
      sym_string_literal,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(183), 7,
      sym_identifier,
      sym_nothing,
      sym_never,
      sym_int_literal,
      anon_sym_true,
      anon_sym_false,
      sym_not_operator,
  [2318] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 5,
      anon_sym_LPAREN,
      sym_float_literal,
      sym_string_literal,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(187), 7,
      sym_identifier,
      sym_nothing,
      sym_never,
      sym_int_literal,
      anon_sym_true,
      anon_sym_false,
      sym_not_operator,
  [2338] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(76), 1,
      sym_qualified_identifier,
    STATE(71), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [2355] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    STATE(76), 1,
      sym_qualified_identifier,
    STATE(71), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [2372] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_round_expression_list_repeat1,
  [2385] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_round_expression_list_repeat1,
  [2398] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_round_expression_list_repeat1,
  [2411] = 4,
    ACTIONS(117), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_BSLASH,
    ACTIONS(209), 1,
      anon_sym_SQUOTE,
    ACTIONS(211), 1,
      anon_sym_COLON,
  [2424] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_round_expression_list_repeat1,
  [2437] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_round_expression_list_repeat1,
  [2450] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
  [2497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_identifier,
  [2504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_identifier,
  [2511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym_identifier,
  [2518] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 56,
  [SMALL_STATE(13)] = 112,
  [SMALL_STATE(14)] = 165,
  [SMALL_STATE(15)] = 218,
  [SMALL_STATE(16)] = 271,
  [SMALL_STATE(17)] = 324,
  [SMALL_STATE(18)] = 377,
  [SMALL_STATE(19)] = 430,
  [SMALL_STATE(20)] = 483,
  [SMALL_STATE(21)] = 536,
  [SMALL_STATE(22)] = 589,
  [SMALL_STATE(23)] = 642,
  [SMALL_STATE(24)] = 695,
  [SMALL_STATE(25)] = 748,
  [SMALL_STATE(26)] = 801,
  [SMALL_STATE(27)] = 854,
  [SMALL_STATE(28)] = 896,
  [SMALL_STATE(29)] = 944,
  [SMALL_STATE(30)] = 994,
  [SMALL_STATE(31)] = 1046,
  [SMALL_STATE(32)] = 1092,
  [SMALL_STATE(33)] = 1134,
  [SMALL_STATE(34)] = 1189,
  [SMALL_STATE(35)] = 1236,
  [SMALL_STATE(36)] = 1277,
  [SMALL_STATE(37)] = 1330,
  [SMALL_STATE(38)] = 1381,
  [SMALL_STATE(39)] = 1434,
  [SMALL_STATE(40)] = 1475,
  [SMALL_STATE(41)] = 1520,
  [SMALL_STATE(42)] = 1548,
  [SMALL_STATE(43)] = 1576,
  [SMALL_STATE(44)] = 1628,
  [SMALL_STATE(45)] = 1660,
  [SMALL_STATE(46)] = 1712,
  [SMALL_STATE(47)] = 1739,
  [SMALL_STATE(48)] = 1765,
  [SMALL_STATE(49)] = 1791,
  [SMALL_STATE(50)] = 1817,
  [SMALL_STATE(51)] = 1845,
  [SMALL_STATE(52)] = 1871,
  [SMALL_STATE(53)] = 1897,
  [SMALL_STATE(54)] = 1923,
  [SMALL_STATE(55)] = 1949,
  [SMALL_STATE(56)] = 1975,
  [SMALL_STATE(57)] = 2001,
  [SMALL_STATE(58)] = 2027,
  [SMALL_STATE(59)] = 2053,
  [SMALL_STATE(60)] = 2078,
  [SMALL_STATE(61)] = 2103,
  [SMALL_STATE(62)] = 2128,
  [SMALL_STATE(63)] = 2153,
  [SMALL_STATE(64)] = 2178,
  [SMALL_STATE(65)] = 2203,
  [SMALL_STATE(66)] = 2228,
  [SMALL_STATE(67)] = 2253,
  [SMALL_STATE(68)] = 2278,
  [SMALL_STATE(69)] = 2298,
  [SMALL_STATE(70)] = 2318,
  [SMALL_STATE(71)] = 2338,
  [SMALL_STATE(72)] = 2355,
  [SMALL_STATE(73)] = 2372,
  [SMALL_STATE(74)] = 2385,
  [SMALL_STATE(75)] = 2398,
  [SMALL_STATE(76)] = 2411,
  [SMALL_STATE(77)] = 2424,
  [SMALL_STATE(78)] = 2437,
  [SMALL_STATE(79)] = 2450,
  [SMALL_STATE(80)] = 2458,
  [SMALL_STATE(81)] = 2466,
  [SMALL_STATE(82)] = 2474,
  [SMALL_STATE(83)] = 2482,
  [SMALL_STATE(84)] = 2490,
  [SMALL_STATE(85)] = 2497,
  [SMALL_STATE(86)] = 2504,
  [SMALL_STATE(87)] = 2511,
  [SMALL_STATE(88)] = 2518,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_expression, 2, 0, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_expression, 4, 0, 11),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 5),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 5),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 1, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualified_identifier, 1, 0, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 3, 0, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualified_identifier, 3, 0, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nominal, 1, 0, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, 0, 6),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 2, 0, 6),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nominal, 1, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_round_expression_list, 5, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_round_expression_list, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_access_expression, 3, 0, 8),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_access_expression, 3, 0, 8),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 1, 0, 3),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 1, 0, 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_round_expression_list, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_round_expression_list, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_round_expression_list, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_round_expression_list, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_round_expression_list, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_round_expression_list, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_literal, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool_literal, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparative_operator, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparative_operator, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_additive_operator, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_additive_operator, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiplicative_operator, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicative_operator, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_round_expression_list_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_round_expression_list_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_expression, 3, 0, 10),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 5, 0, 7),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_expression, 5, 0, 12),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, 0, 4),
  [227] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_peopl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
